darkmode: true

# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Lee Junho
title: Web Full-Stack Engineer
email: junhodori@gmail.com
# website: www.github.com/sproogen/resume-theme

# Social links
# twitter_username: facespics
github_username:  junhodori
# dribbble_username: jekyll
facebook_username: junhodori
# flickr_username: jekyll
instagram_username: junhodori
# linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  저는 9년차 <mark>웹 풀스택</mark> 엔지니어 입니다.

  열정적으로 변화와 도전을 즐기고 있습니다.

  검색엔진 회사를 시작으로 광고플랫폼을 거쳐 현재는 스타트업에서 백엔드팀 리딩을 하며 열심히 성장하고 있습니다.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  나의 취미 생활:
   - StarCraft
   - Riding a bicycle
   - Futsal
   - Health training
   - Camping as a new hobby

#  나의 개인 학습:
#   - Node.js
#   - Redis
#   - Electron
#   - Redis
#   - Mean Stack
#   - Elastic Stack
#   - Kotlin
#   - Docker
#   - Machine Learning
#   - React
#   - WebFlux

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
